name: Deploy Django to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            APP_DIR="/home/${{ secrets.GCP_VM_USER }}/swe_django_app"
            REPO_URL=git@github.com:EshanJayasundara/Django-Web-App-for-SweBench-Evaluation

            # Check if directory exists
            if [ ! -d "$APP_DIR" ]; then
              echo "Cloning the repository..."
              git clone $REPO_URL $APP_DIR
            else
              echo "Repository already cloned. Pulling latest changes..."
              cd $APP_DIR
              git pull origin main
            fi

            # Continue with deployment
            cd $APP_DIR
            source /path/to/your/venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart myapp.service
          EOF
