name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo -e "DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}'\nDEBUG='${{ secrets.DEBUG }}'\nGCP_VM_IP='${{ secrets.GCP_VM_IP }}'" > .env

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
        env:
          DEBUG: "False"
          DJANGO_SECRET_KEY: "test-key"
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'

            export APP_DIR="/home/${{ secrets.GCP_VM_USER }}/swe_django_app"
            export REPO_URL=https://github.com/EshanJayasundara/Django-Web-App-for-SweBench-Evaluation.git
            export DEBUG="${{ secrets.DEBUG }}"
            export DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"
            export DJANGO_SUPERUSER_EMAIL="${{ secrets.DJANGO_SUPERUSER_EMAIL }}"
            export DJANGO_SUPERUSER_USERNAME="${{ secrets.DJANGO_SUPERUSER_USERNAME }}"
            export DJANGO_SUPERUSER_PASSWORD="${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" 
            export GCP_VM_IP = "${{ secrets.GCP_VM_IP }}"

            echo -e "DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}'\nDEBUG='${{ secrets.DEBUG }}'\nAPP_DIR='/home/${{ secrets.GCP_VM_USER }}/swe_django_app'\nGCP_VM_IP='${{ secrets.GCP_VM_IP }}'" > .env

            # Check if directory exists
            if [ ! -d "$APP_DIR" ]; then

              echo "Cloning the repository..."
              git clone $REPO_URL $APP_DIR

              # Continue with deployment
              cd $APP_DIR

              echo "Cloning SWE-bench repo..."
              git clone https://github.com/princeton-nlp/SWE-bench.git

              cd SWE-bench

              echo "Creating SWE-bench venv..."
              python3 -m venv .venv

              echo "Activating SWE-bench venv..."
              source .venv/bin/activate

              echo "Installing SWE-bench dependencies..."
              pip3 install -e .

              echo "Deactivation SWE-bench venv..."
              deactivate

              echo "Go back to $APP_DIR"
              cd ..

              echo "Creating django venv..."
              python3 -m venv .venv
              
              echo "Activating django venv..."
              source .venv/bin/activate

              echo "Installing django dependencies..."
              pip3 install -e .

              echo -e "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY\nDEBUG=$DEBUG\nAPP_DIR=$APP_DIR" > .env

              python manage.py migrate
              python manage.py createsuperuser --noinput

            else

              echo "Repository already cloned. Pulling latest changes..."
              cd $APP_DIR
              git pull origin main

              # Continue with deployment
              cd $APP_DIR

              if [ ! -d SWE-bench ]; then
                echo "Cloning SWE-bench repo..."
                git clone https://github.com/princeton-nlp/SWE-bench.git
              fi
              
              cd SWE-bench

              if [ ! -d .venv ]; then
                echo "Creating new venv..."
                python3 -m venv .venv
                echo "Activating new venv..."
                source .venv/bin/activate
                pip3 install -e .

              else

                echo "Activating existing venv..."
                source .venv/bin/activate
                pip3 install -e .

              fi

              deactivate
              
              cd ..
              
              if [ ! -d .venv ]; then

                echo "Creating new venv..."
                python3 -m venv .venv
                echo "Activating new venv..."
                source .venv/bin/activate
                pip3 install -e .

              else

                echo "Activating existing venv..."
                source .venv/bin/activate
                pip3 install -e .

              fi

              python manage.py migrate

            fi

          EOF
